name: shortly
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./store.json:/app/store.json
    environment:
        - SERVER_ADDRESS=0.0.0.0:8080
        - BASE_URL=http://localhost:8080
        - CLIENT_URL=http://localhost:3000
        - FILE_STORAGE_PATH=/app/store.json
        - DATABASE_DSN=postgres://postgres:postgres@database:5432/shortly-development?sslmode=disable
    networks:
      - shortly-network

  database:
    image: postgres:16.4-alpine
    volumes:
      - shortly-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    networks:
      - shortly-network

networks:
  shortly-network:
    name: shortly-network
    external: false

volumes:
  shortly-database:
