// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/server/gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/server/gateway.go -destination=internal/app/server/gateway_mock.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGRPCGateway is a mock of GRPCGateway interface.
type MockGRPCGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCGatewayMockRecorder
	isgomock struct{}
}

// MockGRPCGatewayMockRecorder is the mock recorder for MockGRPCGateway.
type MockGRPCGatewayMockRecorder struct {
	mock *MockGRPCGateway
}

// NewMockGRPCGateway creates a new mock instance.
func NewMockGRPCGateway(ctrl *gomock.Controller) *MockGRPCGateway {
	mock := &MockGRPCGateway{ctrl: ctrl}
	mock.recorder = &MockGRPCGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCGateway) EXPECT() *MockGRPCGatewayMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockGRPCGateway) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockGRPCGatewayMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockGRPCGateway)(nil).Run))
}

// Shutdown mocks base method.
func (m *MockGRPCGateway) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockGRPCGatewayMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockGRPCGateway)(nil).Shutdown), ctx)
}
