// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/server/pprof.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/server/pprof.go -destination=internal/app/server/pprof_mock.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPprofServer is a mock of PprofServer interface.
type MockPprofServer struct {
	ctrl     *gomock.Controller
	recorder *MockPprofServerMockRecorder
	isgomock struct{}
}

// MockPprofServerMockRecorder is the mock recorder for MockPprofServer.
type MockPprofServerMockRecorder struct {
	mock *MockPprofServer
}

// NewMockPprofServer creates a new mock instance.
func NewMockPprofServer(ctrl *gomock.Controller) *MockPprofServer {
	mock := &MockPprofServer{ctrl: ctrl}
	mock.recorder = &MockPprofServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPprofServer) EXPECT() *MockPprofServerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockPprofServer) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockPprofServerMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPprofServer)(nil).Run))
}

// Shutdown mocks base method.
func (m *MockPprofServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockPprofServerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockPprofServer)(nil).Shutdown), ctx)
}
