// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/service/health.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/service/health.go -destination=internal/app/service/health_mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHealthServiceInterface is a mock of HealthServiceInterface interface.
type MockHealthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockHealthServiceInterfaceMockRecorder is the mock recorder for MockHealthServiceInterface.
type MockHealthServiceInterfaceMockRecorder struct {
	mock *MockHealthServiceInterface
}

// NewMockHealthServiceInterface creates a new mock instance.
func NewMockHealthServiceInterface(ctrl *gomock.Controller) *MockHealthServiceInterface {
	mock := &MockHealthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockHealthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthServiceInterface) EXPECT() *MockHealthServiceInterfaceMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockHealthServiceInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockHealthServiceInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockHealthServiceInterface)(nil).Ping), ctx)
}
