// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (uuid, long_url, short_code) VALUES ($1, $2, $3) RETURNING uuid, long_url, short_code
`

type CreateURLParams struct {
	UUID      uuid.UUID
	LongURL   string
	ShortCode string
}

type CreateURLRow struct {
	UUID      uuid.UUID
	LongURL   string
	ShortCode string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error) {
	row := q.db.QueryRow(ctx, createURL, arg.UUID, arg.LongURL, arg.ShortCode)
	var i CreateURLRow
	err := row.Scan(&i.UUID, &i.LongURL, &i.ShortCode)
	return i, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT uuid, long_url, short_code FROM urls WHERE short_code = $1
`

type GetURLByShortCodeRow struct {
	UUID      uuid.UUID
	LongURL   string
	ShortCode string
}

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (GetURLByShortCodeRow, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i GetURLByShortCodeRow
	err := row.Scan(&i.UUID, &i.LongURL, &i.ShortCode)
	return i, err
}

const healthCheck = `-- name: HealthCheck :one
SELECT 1
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
