// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repository/memory.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repository/memory.go -destination=internal/app/repository/memory_mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInMemory is a mock of InMemory interface.
type MockInMemory struct {
	ctrl     *gomock.Controller
	recorder *MockInMemoryMockRecorder
	isgomock struct{}
}

// MockInMemoryMockRecorder is the mock recorder for MockInMemory.
type MockInMemoryMockRecorder struct {
	mock *MockInMemory
}

// NewMockInMemory creates a new mock instance.
func NewMockInMemory(ctrl *gomock.Controller) *MockInMemory {
	mock := &MockInMemory{ctrl: ctrl}
	mock.recorder = &MockInMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemory) EXPECT() *MockInMemoryMockRecorder {
	return m.recorder
}

// CreateMemento mocks base method.
func (m *MockInMemory) CreateMemento() *Memento {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMemento")
	ret0, _ := ret[0].(*Memento)
	return ret0
}

// CreateMemento indicates an expected call of CreateMemento.
func (mr *MockInMemoryMockRecorder) CreateMemento() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMemento", reflect.TypeOf((*MockInMemory)(nil).CreateMemento))
}

// Get mocks base method.
func (m *MockInMemory) Get(ctx context.Context, shortCode string) (*URL, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortCode)
	ret0, _ := ret[0].(*URL)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInMemoryMockRecorder) Get(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInMemory)(nil).Get), ctx, shortCode)
}

// Restore mocks base method.
func (mr *MockInMemory) Restore(m *Memento) {
	mr.ctrl.T.Helper()
	mr.ctrl.Call(mr, "Restore", m)
}

// Restore indicates an expected call of Restore.
func (mr *MockInMemoryMockRecorder) Restore(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockInMemory)(nil).Restore), m)
}

// Set mocks base method.
func (m *MockInMemory) Set(ctx context.Context, url URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockInMemoryMockRecorder) Set(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockInMemory)(nil).Set), ctx, url)
}
